### ISSUE TITLE
Library could not be built on Solaris 

### ISSUE THREAD

**Issue by avysotsk** [bloomberg/bde#204]
GCC verion is 4.8.2
$ waf configure --check-c-compiler=gcc --check-cxx-compiler=gcc
$ waf build --test=build --abi-bits=64  -v 
[.. skipped ...]

/bin/g++ -Wcast-align -Wcast-qual -Wall -Wextra -Wformat-security -Wformat-y2k -Winit-self -Wno-long-long -Wno-unknown-pragmas -Wpacked -Wpointer-arith -Wwrite-strings -Wno-unused-value -Wno-char-subscripts -Wsign-compare -Wparentheses -Wlogical-op -Wstrict-overflow -Wvla -Wvolatile-register-var -fdiagnostics-show-option -Wno-sign-conversion -Wconversion -Waddress -Wtype-limits -Wcast-align -Wsign-compare -Wformat -Woverflow -Wlarger-than-100000 -Werror=cast-qual -m64 -ftemplate-depth-150 -DBDE_BUILD_TARGET_DBG -DBDE_BUILD_TARGET_EXC -DBDE_BUILD_TARGET_MT --param ggc-min-expand=30 -mcpu=niagara2 -fexceptions -g -D_POSIX_PTHREAD_SEMANTICS -D_REENTRANT -pthreads -DBSLS_IDENT_OFF -I/BSL/gcc/bde/groups/btl/btlso -I/BSL/gcc/bde/groups/btl/btls -I/BSL/gcc/bde/groups/btl/btlb -I/BSL/gcc/bde/groups/btl/btlscm -I/BSL/gcc/bde/groups/bdl/bdlscm -I/BSL/gcc/bde/groups/bdl/bdlf -I/BSL/gcc/bde/groups/bdl/bdlb -I/BSL/gcc/bde/groups/bdl/bdlsb -I/BSL/gcc/bde/groups/bdl/bdlma -I/BSL/gcc/bde/groups/bdl/bdlc -I/BSL/gcc/bde/groups/bdl/bdlt -I/BSL/gcc/bde/groups/bdl/bdlat -I/BSL/gcc/bde/groups/bdl/bdlde -I/BSL/gcc/bde/groups/bdl/bdls -I/BSL/gcc/bde/groups/bdl/bdldfp -I/BSL/gcc/bde/groups/bdl/bdlcc -I/BSL/gcc/bde/groups/bdl/bdlmt -I/BSL/gcc/bde/groups/bsl/bsls -I/BSL/gcc/bde/groups/bsl/bslscm -I/BSL/gcc/bde/groups/bsl/bsldoc -I/BSL/gcc/bde/groups/bsl/bslmf -I/BSL/gcc/bde/groups/bsl/bslma -I/BSL/gcc/bde/groups/bsl/bslalg -I/BSL/gcc/bde/groups/bsl/bslh -I/BSL/gcc/bde/groups/bsl/bsltf -I/BSL/gcc/bde/groups/bsl/bslstl -I/BSL/gcc/bde/groups/bsl/bsl+bslhdrs -I/BSL/gcc/bde/groups/bsl/bsl+stdhdrs -I/BSL/gcc/bde/groups/bsl/bslim -I/BSL/gcc/bde/groups/bsl/bslmt -I/BSL/gcc/bde/groups/bsl/bslx -I/BSL/gcc/bde/build/thirdparty/decnumber -I/BSL/gcc/bde/thirdparty/decnumber -I/BSL/gcc/bde/build/thirdparty/inteldfp/LIBRARY/src -I/BSL/gcc/bde/thirdparty/inteldfp/LIBRARY/src ../groups/btl/btlso/btlso_defaulteventmanager_poll.cpp -c -o /BSL/gcc/bde/build/groups/btl/btlso/btlso_defaulteventmanager_poll.cpp.1.o'
[btlso_defaulteventmanager_devpoll.cpp (ERROR)] <<<<<<<<<<
../groups/btl/btlso/btlso_defaulteventmanager_devpoll.cpp: In member function 'virtual int BloombergLP::btlso::DefaultEventManager<BloombergLP::btlso::Platform::DEVPOLL>::dispatch(const BloombergLP::bsls::TimeInterval&, int)':
../groups/btl/btlso/btlso_defaulteventmanager_devpoll.cpp:188:45: warning: conversion to 'int' from 'bsl::Vector_ImpBase<pollfd>::size_type {aka long unsigned int}' may alter its value [-Wconversion]
             int oldlength = d_signaled.size();
                                             ^
../groups/btl/btlso/btlso_defaulteventmanager_devpoll.cpp:218:76: warning: conversion to 'int' from 'BloombergLP::bsls::Types::Int64 {aka long long int}' may alter its value [-Wconversion]
                                       + curr_timeout.nanoseconds()/1000000 + 1;
                                                                            ^
../groups/btl/btlso/btlso_defaulteventmanager_devpoll.cpp:220:33: error: 'min' is not a member of 'bsl'
             dopoll.dp_timeout = bsl::min(
                                 ^
../groups/btl/btlso/btlso_defaulteventmanager_devpoll.cpp:220:33: note: suggested alternative:
In file included from /usr/gcc/4.8/include/c++/4.8.2/algorithm:61:0,
                 from /BSL/gcc/bde/groups/bsl/bsl+stdhdrs/algorithm:33,
                 from /BSL/gcc/bde/groups/bsl/bslalg/bslalg_swaputil.h:112,
                 from /BSL/gcc/bde/groups/bsl/bslstl/bslstl_simplepool.h:213,
                 from /BSL/gcc/bde/groups/bsl/bslstl/bslstl_bidirectionalnodepool.h:190,
                 from /BSL/gcc/bde/groups/bsl/bslstl/bslstl_hashtable.h:1471,
                 from /BSL/gcc/bde/groups/bsl/bslstl/bslstl_unorderedmap.h:883,
                 from /BSL/gcc/bde/groups/bsl/bsl+bslhdrs/bsl_unordered_map.h:47,
                 from /BSL/gcc/bde/groups/btl/btlso/btlso_defaulteventmanager_devpoll.h:313,
                 from ../groups/btl/btlso/btlso_defaulteventmanager_devpoll.cpp:10:
/usr/gcc/4.8/include/c++/4.8.2/bits/stl_algobase.h:239:5: note:   'std::min'
     min(const _Tp& __a, const _Tp& __b, _Compare __comp)
     ^

**Comment by mversche** [comment]
Odd -- I don't see this error in our nightly builds on Solaris gcc (though we have 4.5 and 4.9).

Seems straight forward to fix in either case.

**Comment by abeels** [comment]
I have replicated the error while validating the just-pushed updates to master today.  Something in our internal build configuration is masking the error.

**Comment by abeels** [comment]
Resolved by b80817c028ee764c0bb848cb49634e779124f513
