### ISSUE TITLE
Build failure on Clang 3.1 looking for __CLANG_GNUC__ and similar symbols

### ISSUE THREAD

**Issue by kpfleming** [bloomberg/bde#60]
In a build using Clang 3.1 as packaged in openSUSE 12.2, the following errors occur:

```
../groups/bsl/bsls/bsls_annotation.t.cpp:530:61: error: use of undeclared identifier '__CLANG_GNUC__'
           cout << "BSLS_PLATFORM_CMP_VER_MAJOR" " = " << ((__CLANG_GNUC__ * 10000 + __CLANG_GNUC_MINOR__ * 100)) << endl;;
                                                            ^
../groups/bsl/bsls/bsls_annotation.t.cpp:530:86: error: use of undeclared identifier '__CLANG_GNUC_MINOR__'
           cout << "BSLS_PLATFORM_CMP_VER_MAJOR" " = " << ((__CLANG_GNUC__ * 10000 + __CLANG_GNUC_MINOR__ * 100)) << endl;;
                                                                                     ^
```

and

```
../groups/bsl/bsls/bsls_platform.t.cpp:552:30: error: use of undeclared identifier '__CLANG_GNUC__'
            { aSsErT(!(0 <= (__CLANG_GNUC__ * 10000 + __CLANG_GNUC_MINOR__ * 100)), "0 <= (__CLANG_GNUC__ * 10000 + __CLANG_GNUC_MINOR__ * 100)", 552); }; if (veryVerbose) cout << "\t""BSLS_PLATFORM_CMP_VER_MAJOR"" = " << (__CLANG_GNUC__ * 10000 + __CLANG_GNUC_MINOR__ * 100) << endl;;
                             ^
../groups/bsl/bsls/bsls_platform.t.cpp:552:55: error: use of undeclared identifier '__CLANG_GNUC_MINOR__'
            { aSsErT(!(0 <= (__CLANG_GNUC__ * 10000 + __CLANG_GNUC_MINOR__ * 100)), "0 <= (__CLANG_GNUC__ * 10000 + __CLANG_GNUC_MINOR__ * 100)", 552); }; if (veryVerbose) cout << "\t""BSLS_PLATFORM_CMP_VER_MAJOR"" = " << (__CLANG_GNUC__ * 10000 + __CLANG_GNUC_MINOR__ * 100) << endl;;
                                                      ^
../groups/bsl/bsls/bsls_platform.t.cpp:552:224: error: use of undeclared identifier '__CLANG_GNUC__'
            { aSsErT(!(0 <= (__CLANG_GNUC__ * 10000 + __CLANG_GNUC_MINOR__ * 100)), "0 <= (__CLANG_GNUC__ * 10000 + __CLANG_GNUC_MINOR__ * 100)", 552); }; if (veryVerbose) cout << "\t""BSLS_PLATFORM_CMP_VER_MAJOR"" = " << (__CLANG_GNUC__ * 10000 + __CLANG_GNUC_MINOR__ * 100) << endl;;
                                                                                                                                                                                                                               ^
../groups/bsl/bsls/bsls_platform.t.cpp:552:249: error: use of undeclared identifier '__CLANG_GNUC_MINOR__'
            { aSsErT(!(0 <= (__CLANG_GNUC__ * 10000 + __CLANG_GNUC_MINOR__ * 100)), "0 <= (__CLANG_GNUC__ * 10000 + __CLANG_GNUC_MINOR__ * 100)", 552); }; if (veryVerbose) cout << "\t""BSLS_PLATFORM_CMP_VER_MAJOR"" = " << (__CLANG_GNUC__ * 10000 + __CLANG_GNUC_MINOR__ * 100) << endl;;
                                                                                                                                                                                                                                                        ^
```

Based on a bit of research, these symbols do not appear to be part of a standard LLVM/Clang build, and thus the code should not be relying on their presence.
