### PR TITLE
gcc/clang BSLS_PERFORMANCEHINT_UNLIKELY_HINT impl

### PR DESCRIPTION
**Pull request by gstrauss**
implement BSLS_PERFORMANCEHINT_UNLIKELY_HINT for gcc and clang when the
compilers support __attribute__(cold)

### CODE REVIEW

**Comment by mversche** [comment]
I've updated the phabricator.   But, this code doesn't compile on gcc 4.8:

/bb/mbigc/mbig2186/bsl-oss/groups/bsl/bsls/bsls_performancehint.h:543:57: error: missing binary operator before token "("
  || (defined(BSLS_PLATFORM_CMP_CLANG) && __has_attribute(cold))

**Comment by mversche** [comment]
Following up on our conversation, I think the fix for this should made entirely in the context of `bsls_performancehint` (i.e., we should *not* try and generalize something for `__has_attribute` at this time).  I can think of a couple ways that could reasonably be done.

e.g.,
```
    #ifdef CLANG
    #define BSLS_PERFORMANCEHINT__HAS_ATTRIBUTE_COLD __has_attribute(cold)
    #else
    #define BSLS_PERFORMANCEHINT__HAS_ATTRIBUTE_COLD 0
    #endif
```

or

```
#define  BSLS_PERFORMANCEHINT__HAS_ATTRIBUTE(X) __has_attribute((X))
```

etc...

**Comment by gstrauss** [comment]
Made another attempt.  Bonus: this compiles on compilers other than clang, too. :)
Please review f922f7f
